/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // New color palette
        navy: {
          DEFAULT: "#2F4156",
          50: "#EFF1F3",
          100: "#DEE3E7",
          200: "#BDC8D0",
          300: "#9CADB8",
          400: "#7B91A1",
          500: "#567C8D",
          600: "#476473",
          700: "#374D59",
          800: "#2F4156",
          900: "#1E2A37",
        },
        teal: {
          DEFAULT: "#567C8D",
          50: "#F2F5F7",
          100: "#E5EBEF",
          200: "#CCD8DE",
          300: "#B2C4CE",
          400: "#99B1BE",
          500: "#7F9DAE",
          600: "#658A9E",
          700: "#567C8D",
          800: "#455F6B",
          900: "#334550",
        },
        skyblue: {
          DEFAULT: "#C8D9E6",
          50: "#FCFDFD",
          100: "#F8FAFB",
          200: "#F0F4F7",
          300: "#E8EFF3",
          400: "#E0E9F0",
          500: "#D8E4EC",
          600: "#D0DEE8",
          700: "#C8D9E6",
          800: "#9DB9CF",
          900: "#7399B8",
        },
        beige: {
          DEFAULT: "#F5EFEB",
          50: "#FEFDFB",
          100: "#FCFAF8",
          200: "#FAF7F5",
          300: "#F7F4F1",
          400: "#F6F1ED",
          500: "#F5EFEB",
          600: "#E4D3C6",
          700: "#D3B8A2",
          800: "#C19C7D",
          900: "#B08159",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        neutral: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "Inter",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        display: [
          "var(--font-poppins)",
          "Poppins",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      spacing: {
        "content-sm": "1rem",
        "content-md": "1.5rem",
        "content-lg": "2rem",
      },
      boxShadow: {
        subtle: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "subtle-md": "0 2px 4px 0 rgb(0 0 0 / 0.05)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
